### ISSUE TITLE
Can't Display Images.

### ISSUE THREAD

**Issue by MrPresident2** [julien-nc/welcome#22]
Hello, 
I'm having a problem that might be a user error.
I'm trying to add pictures to the MK file, and under visual studio code viewer everything works fine, but when  I upload the MK the pics won't load.

This is what I wrote : `<img src="https://i.pinimg.com/originals/39/bf/c0/39bfc051c9de1e3a71c5210755e4edf7.gif" width="50" height="50" />`

maybe anyone can help me with that? thanks.

**Comment by Wizlonex** [comment]
Bump.  Same issue for me.  I have tried to add different sized images to the Readme.md file and none of them gets displayed.  All I see is as shown attached.  Fails with small jpg and .png files.  Running Nextcloud 25.01.

The app release notes suggest images are supported.  Is there a specific format we have to follow to display an image?

THAN
![Screenshot from 2022-11-28 16-15-08](https://user-images.githubusercontent.com/35621692/204382676-fd8d6199-aae9-4f3d-8e68-0e4f95cf1c73.png)
K YOU

**Comment by daburger** [comment]
same issue with me. Still no update 6 months later?

**Comment by julien-nc** [comment]
Well, raw html content is not supported in markdown files.

This app was supposed to support images inserted when editing with the Text app but since the image link format has changed, it needed some adjustments. It is now fixed in v1.0.3.
I also added support for http targets in markdown image links.

So, to put images in the widget, you may:
* use the Text app to edit the markdown file and insert an image from  there (both "Upload from computer" and "Insert from files" should work)
* or edit the markdown file with any text editor and add image links like `![whatever title](https://yay.org/my.gif)`

Example:
![image](https://user-images.githubusercontent.com/11291457/209411738-522eaf62-f430-4eec-902e-e8f4de7c33be.png)
with the markdown file content (edited with Text and then with an external editor to add the http link):
``` markdown
Hey hey

Image from NC files:
![agony-19.jpg](.attachments.12050/agony-19.jpg)

External image (https link):
![zegif](https://i.pinimg.com/originals/39/bf/c0/39bfc051c9de1e3a71c5210755e4edf7.gif)

Cheers
```

I also adjusted the image style in the widget. Instead of a fixed height and variable width, they now just have a max width of 250px and a max height of 150px.

It would be nice if someone could try it.

**Comment by Wizlonex** [comment]
Either I have some goofy setting in apache2 or Nextcloud that is incorrect of I am just plain doing something incredibly stupid because I cannot get any images to work in any manner.  I tried replicating your example file using both a plain offline text editor and the built in editor to Nextcloud and neither works (I replaced the internal image with a similar one I had in my instance).  Dashboard wouldn't even display the i.pinimg.com image you have above, yet my browser goes striaght to it
![Screenshot from 2022-12-25 07-34-42](https://user-images.githubusercontent.com/35621692/209460425-e1e80ab4-2ec2-4bac-94d1-18bbfd4885fa.png)
.

I don't think it's you, as your illustration above shows this can indeed work.  I shall stick with emoji's and plain text until my brain fog clears up.

THANK YOU.  Sorry I am unable to report a complete success.

Andrew

**Comment by julien-nc** [comment]
@Wizlonex Could you tell us more about your context?
* NC version
* Welcome app version
* markdown file content
* errors in the browser console (or the network tab)

**Comment by julien-nc** [comment]
I tried on NC 24, 25 and 26 (master), it works fine on my side.
One thing worth mentioning: images from NC files are obtained with the preview endpoint. So you need the previews to work for that file type. Have you tried with PNG or JPEG images?

For the http link it could be a CSP issue but I can't tell until I reproduce the bug.

**Comment by Wizlonex** [comment]
> 

NC 25.0.2
Apache/2.4.52 (Ubuntu)
php 8.1 (I enable php-fpm vs php - is that a potential problem?)

There are no Nextcloud server log entries at all when I create or display the Readme.md Welcome file. 

I updated the app today to version 1.04 and it still does not work for me - I am seriously thinking I am just too stupid to get this to work.

I have tried .gif and .png public files (ones which I can access via Chrome) and I get the same errors.  I have tried uploading from Nextcloud files, but also images directly from my computer and I get the same output no matter what I do

Here's a link to a copy of the last Readme.md file I tried (one of very many failed attempts):

https://cloud.ogselfhosting.com/index.php/s/TtBEcYJSqXzwMf6

Attached are how the Readme.md file looks in my editor and also the actual dashboard display (refreshed).  I would be happy to try a Readme.md file created e.g. by you or anyone else (I need a download link please - I don't think I should trust copy/pasting).

I am so sorry for causing you grief with this.  I suspect I have a config missing somewhere else, and it's only showing up here.

THANK YOU for your time and for the app (which is still very useful to me even without images)

Andrew
![Screenshot from 2022-12-27 11-17-46](https://user-images.githubusercontent.com/35621692/209693205-a06ccb97-72ca-44a6-b74d-892e9fbc4ff3.png)
![Screenshot from 2022-12-27 11-18-05](https://user-images.githubusercontent.com/35621692/209693218-80989c34-f165-40f3-8428-961c869cfba3.png)

**Comment by julien-nc** [comment]
> I am so sorry for causing you grief with this.

Don't be sorry. It is most likely an error on my side. It's actually very nice that you persist on helping to find the cause of this issue.

Something I forgot to mention: For the moment, images are only displayed if the current user has access to them. This is clearly not convenient as it means the owner of the markdown file should share the attachment folder to all NC users...

I'll fix that very soon by accessing the images via a new endpoint in the welcome app which will provide any image in the markdown file's attachment folder.

Anyway this does not explain why the http links don't work for you.
The remaining thing you didn't provide is the browser console error log (and request errors in the network tab). If it says something about the "Content Security Policy" it means the Welcome app fails to inject a custom CSP.

I checked with your file, the wikimedia image link works fine on my side, with both Firefox and Chromium.

![image](https://user-images.githubusercontent.com/11291457/209701851-2055d6ac-dbb0-47d0-a9ab-a996f1beac5e.png)

**Comment by julien-nc** [comment]
v1.0.5 includes the fix to get image attachments. Can you try it?

**Comment by Wizlonex** [comment]
Yes sir - just as soon as it shows up on my app list (it's not there now as of the timestamp of this post), I will update and report back.  Thank  you!!

**Comment by Wizlonex** [comment]
> > I am so sorry for causing you grief with this.
> 
> Don't be sorry. It is most likely an error on my side. It's actually very nice that you persist on helping to find the cause of this issue.
> 
> Something I forgot to mention: For the moment, images are only displayed if the current user has access to them. This is clearly not convenient as it means the owner of the markdown file should share the attachment folder to all NC users...
> 
> I'll fix that very soon by accessing the images via a new endpoint in the welcome app which will provide any image in the markdown file's attachment folder.
> 
> Anyway this does not explain why the http links don't work for you. The remaining thing you didn't provide is the browser console error log (and request errors in the network tab). If it says something about the "Content Security Policy" it means the Welcome app fails to inject a custom CSP.
> 
> I checked with your file, the wikimedia image link works fine on my side, with both Firefox and Chromium.
> 
> ![image](https://user-images.githubusercontent.com/11291457/209701851-2055d6ac-dbb0-47d0-a9ab-a996f1beac5e.png)

I am using Chrome (up to date) on Linux Mint (20.3 - a slightly dated version).  Hitting F12 on the screen shows an error for the 'flag of the US' link.  I am not particulary good at understanding these, so I just took a screenshots that I hope can be useful.  I don't really know what I am doing with the F12 options, so I am probably not useful for you.  I am willing to create a temporary account on my instance for you so you play with it and read the browser information.  Message me with a username and password and I can create a temporary account.

I also tried this with Chromium and Firefox browsers (on same linux Minto desktop) and I get the exact same issues, so I think it's not the browser.

FYI I am accessing my Nextcloud via cloudflare - is that possibly an issue here?  I will see if I cantemporarily disable php-fpm to see if that's somehow at fault.  Please note I do not run the preview-generator app on my system (in case that is also part of the problem).

I am still running 1.04 as 1.05 has still not shown up in my app store, but I will monitor it and will report back promptly.

Thank you for your patience.  Happy Holidays to you!

Andrew

![Screenshot from 2022-12-27 13-01-02](https://user-images.githubusercontent.com/35621692/209705384-a1b1b63d-738a-4cb5-9c45-6095a9931a43.png)
![Screenshot from 2022-12-27 13-01-02](https://user-images.githubusercontent.com/35621692/209705421-7614978b-9d2e-4530-a2be-b5c86b3e3b36.png)

**Comment by daburger** [comment]
I too am using nextcloud via cloudflare and still having the same issue.
Although I am pretty sure I tried this before using cloudflare and still
didn't work.

Sorry I haven't been as helpful with troubleshooting. Christmas holidays
and all.

Happy to help where I can also.

**Comment by Wizlonex** [comment]
Hi again.

1.05 did not fix this for me.  Sorry!

**Comment by julien-nc** [comment]
Ok another bug down. Thanks @Wizlonex for the test account.
My bad, there was a mistake when replacing image paths with urls based on file IDs. When checking if the image file exists, the "url encoded" path was used instead of the decoded one... So basically, any special character in image file names was problematic.

v1.0.6 should fix this. It would be nice if someone could try it.

@Wizlonex In your NC instance, please add a markdown image link (like the wikimedia us png flag you used before) so I can see what's wrong with http links.

**Comment by Wizlonex** [comment]
I am very pleased to report that using version 1.06 of the App has fixed all the problems for me.  I can embed an image located in the Nextcloud instance, and/or I can upload one from my pc, and/or I can link to e.g. a .gif on the web and they ALL now display in the Welcome widget.  WOOHOO!  Attached screenshot of my test Welcome widget.

THANK YOU VERY MUCH, and I was so glad I could at least help point this for you.

Andrew
![Screenshot from 2022-12-28 06-18-32](https://user-images.githubusercontent.com/35621692/209804276-9abbe209-c3e4-401f-9c31-3aba0a7838b6.png)

**Comment by julien-nc** [comment]
@Wizlonex That's great news. Thanks again for your patience.

**Comment by daburger** [comment]
Ok, I finally got around to testing and can also confirm it is working now. Absolute legend @julien-nc! Appreciate the quick response!
